name: adversarial-sensitivity

channels:
  - pytorch
  - defaults

dependencies:
  - python=3.13

  - pytorch
  - torchvision
  - pandas
  - scikit-image
  - scikit-learn
  - matplotlib
  - tqdm
  - numpy
  - pywavelets
  - pillow

  - pip
  - pip:
      - einops
      - open_clip_torch
      - timm
